use_frameworks!

target 'Coordinators_Example' do
  pod 'Coordinators', :path => '../'

  target 'Coordinators_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
