use_frameworks!

target 'Coordinators_Example' do
  pod 'Coordinators', :path => '../'

  target 'Coordinators_Tests' do
    inherit! :search_paths

    pod 'Quick', '1.3.2'
    pod 'Nimble', '7.3.1'
  end
end
