language: objective-c
osx_image: xcode10.1
install:
- gem install bundler
- bundle install
- bundle exec pod repo update
- cd Example
- bundle exec pod install
- ls Pods/Nimble
script:
- cd Example
- bundle exec fastlane test
